### ISSUE TITLE
Updating state using previous state not in callback? 

### ISSUE THREAD

**Issue by vfonic** [markerikson/project-minimek#17]
Hey,

Thanks for great tutorial!

 I'm just following, looking at where to keep form state so that it doesn't re render the entire tree for every input.

I noticed you're using previous / current state in onChange method, but you're not calling setState with callback function:
https://github.com/markerikson/project-minimek/blob/c321c35e7766705eb11517696ad11f385181bae2/src/common/components/FormEditWrapper.jsx#L53

Is there any specific reason why?

Thanks!

**Comment by markerikson** [comment]
Mmm.... no particular reason. I don't think I was as comfortable using the `setState` updater function at the time, and so it wasn't something I thought about using, I guess.
